on:
  push:
    tags:
      - 'v*'
name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    #needs: [ test ]
    steps:
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_TOKEN }}
    - name: Check out code
      uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_TOKEN }}
        DOCKER_REGISTRY: docker.pkg.github.com
      with:
        args: release
      if: success()